config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :answers
  resources :questions
  devise_for :users

  post "like/:id", to: "answers#like", as: "like_answer"

  root "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question, counter_cache: true
  has_many :likeables, dependent: :destroy
  has_many :likes, through: :likeables, source: :user

  validates :description, presence: true
  validates :user_id, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/likeable.rb
# frozen_string_literal: true

class Likeable < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :user_id, presence: true

  paginates_per 8
  include PgSearch::Model

  pg_search_scope :pg_search,
                  against: %i[title description],
                  using: {
                    tsearch: {
                      any_word: true
                    }
                  }

  def self.search(query)
    return all unless query.present?

    pg_search(query)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :likeables, dependent: :destroy
  has_many :liked_answers, through: :likeables, source: :answer

  def like(answer)
    if liked_answers.include?(answer)
      liked_answers.destroy(answer)
    else
      liked_answers << answer
    end
  end

  def liked?(answer)
    liked_answers.include?(answer)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit update destroy like]
  before_action :set_answer, only: %i[show edit update destroy]

  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def edit
  end

  def like
    @answer = Answer.find(params[:id])
    current_user.like(@answer)
    redirect_to question_url(@answer.question)
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @question = @answer.question

    respond_to do |format|
      if @answer.save
        format.html do
          redirect_to question_url(@answer.question),
                      notice: "Answer was successfully created."
        end
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render "questions/show", status: :unprocessable_entity }
        format.json do
          render json: @answer.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html do
          redirect_to answer_url(@answer),
                      notice: "Answer was successfully updated."
        end
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @answer.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @answer.destroy

    respond_to do |format|
      format.html do
        redirect_to answers_url, notice: "Answer was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def answer_params
    params.require(:answer).permit(:description, :question_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit update destroy]

  before_action :set_question, only: %i[show edit update destroy]
  before_action :set_current_user_questions

  def index
    @questions =
      Question.search(params[:q]).includes(:user).order(created_at: :desc).page(
        params[:page]
      )
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html do
          redirect_to question_url(@question),
                      notice: "Question was successfully created."
        end
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @question.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    @question = current_user.questions.find(params[:id])

    respond_to do |format|
      if @question.update(question_params)
        format.html do
          redirect_to question_url(@question),
                      notice: "Question was successfully updated."
        end
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @question.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html do
        redirect_to questions_url,
                    notice: "Question was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.includes(:answers, :user).find(params[:id])
  end

  def set_current_user_questions
    @current_user_questions =
      Question.where(user: current_user).order(created_at: :desc)
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(
                 formats: :html,
                 status: :unprocessable_entity
               )
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def query_array
    params[:q].to_s.split(' ')
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div class="post" id="<%= dom_id answer %>">
  <div class="topwrap">
    <div class="userinfo pull-left">
      <div class="avatar">
        <img src="<%= answer.user.avatar || '/site_assets/avatar2.jpg' %>" alt="">
        <div class="status red">&nbsp;</div>
      </div>
      <div class="icons">
        <img src="/site_assets/icon3.jpg" alt=""><img src="/site_assets/icon4.jpg" alt=""><img src="/site_assets/icon5.jpg" alt=""><img src="/site_assets/icon6.jpg" alt="">
      </div>
    </div>
    <div class="posttext pull-left">
      <p><%= answer.description %></p>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="postinfobot">
    <div class="posted pull-left"><i class="fa fa-clock-o"></i> Posted on : <%= h(answer.created_at) %></div>
    <div class="likeblock pull-left">
      <a data-turbo-method="post" href="<%= like_answer_path(answer) %>" class="up"><i class="fa fa-thumbs-o-up"></i><%= answer.likes.count %></a>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/answers/_form.html.erb
<div class="post">
  <%= form_with(model: answer) do |form| %>
    <div class="topwrap">
      <div class="userinfo pull-left">
        <div class="avatar">
          <img src="<%= current_user.avatar ||  '/site_assets/avatar.jpg' %>" alt="">
          <div class="status red">&nbsp;</div>
        </div>
        <div class="icons">
          <img src="/site_assets/icon3.jpg" alt=""><img src="/site_assets/icon4.jpg" alt=""><img src="/site_assets/icon5.jpg" alt=""><img src="/site_assets/icon6.jpg" alt="">
        </div>
      </div>
      <div class="posttext pull-left">
        <div class="textwraper">
          <div class="postreply">Post an answer</div>
          <%= form.text_area :description , placeholder: "Type your message here"%>
          <%= form.hidden_field :question_id %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="postinfobot">
      <div class="pull-right postreply">
        <div class="pull-left"><button type="submit" class="btn btn-primary">Post Reply</button></div>
        <div class="clearfix"></div>
      </div>
      <div class="clearfix"></div>
    </div>
  <% end %>
</div>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Show this answer", @answer %> |
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Answers</h1>

<div id="answers">
  <% @answers.each do |answer| %>
    <%= render answer %>
    <p>
      <%= link_to "Show this answer", answer %>
    </p>
  <% end %>
</div>

<%= link_to "New answer", new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @answer %>

<div>
  <%= link_to "Edit this answer", edit_answer_path(@answer) %> |
  <%= link_to "Back to answers", answers_path %>

  <%= button_to "Destroy this answer", @answer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dentally</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <link rel="stylesheet" href="/site_assets/font-awesome.min.css">
  <body>
    <div class="container-fluid">
      <!-- Slider -->
      <div class="tp-banner-container" style="overflow: visible;">
        <div class="tp-banner revslider-initialised tp-simpleresponsive" style="max-height: 278px; height: 278px;" id="revslider-340">
          <ul style="display: block; overflow: hidden; width: 100%; height: 100%; max-height: none;">
            <!-- SLIDE  -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="1500" style="width: 100%; height: 100%; overflow: hidden; visibility: visible; left: 0px; top: 0px; z-index: 20; opacity: 1;">
              <!-- MAIN IMAGE -->
              <div class="slotholder" style="width:100%;height:100%;">
                <div style="background-color: rgba(0, 0, 0, 0);
    background-repeat: no-repeat;
    background-image: url(/site_assets/slide.jpg);
    background-size: cover;
    background-position: left top;
    width: 100%;
    height: 100%;
    opacity: 1;
    position: relative;"></div>
              </div>
              <!-- LAYERS -->
            </li>
          </ul>
          <div class="tp-loader" style="display: none;"></div>
          <div class="tp-bannertimer" style="visibility: hidden; width: 0%;"></div>
        </div>
      </div>
      <!-- //Slider -->
      <div class="headernav">
        <div class="container">
          <div class="row">
            <div class="col-lg-1 col-xs-3 col-sm-2 col-md-2 logo ">
              <a href=" /"><img src="/site_assets/logo.jpg" alt=""></a>
            </div>
            <div class="col-lg-3 col-xs-9 col-sm-5 col-md-3 selecttopic">
              <div class="dropdown">
                <a data-toggle="dropdown" href="/"> Questions</a> <b class="caret"></b>
              </div>
            </div>
            <div class="col-lg-4 search hidden-xs hidden-sm col-md-3">
              <div class="wrap">
                <form action="/" method="get" class="form">
                  <div class="pull-left txt"><input autocomplete="off" name="q" value="<%= params[:q]%>" type="text" class="form-control" placeholder="Search Questions"></div>
                  <div class="pull-right"><button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button></div>
                  <div class="clearfix"></div>
                </form>
              </div>
            </div>
            <div class="col-lg-4 col-xs-12 col-sm-5 col-md-4 avt">
              <div class="stnt pull-left">
                <form action="<%= new_question_path%>" method="get" class="form">
                  <button class="btn btn-primary">Ask a new question</button>
                </form>
              </div>
              <% if current_user %>
                <div class="env pull-left">
                  <%= button_to("Log Out", destroy_user_session_path, method: :delete) %>
                </div>
                <div class="avatar pull-left dropdown">
                  <a data-toggle="dropdown" href="#"><img src="<%= current_user.avatar || '/site_assets/avatar.jpg'%>" alt=""></a> <b class="caret"></b>
                  <div class="status green">&nbsp;</div>
                </div>
              <% else %>
                <div class="env pull-left">
                  <%= button_to("Sign in", new_user_session_path) %>
                </div>
              <%end%>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
      <% if notice %>
        <section class="content">
          <div class="container">
            <div class="row" style="color: green">
              <div class="col-lg-13" style='text-align: center;margin: 10px;'>
                <%= notice %>
              </div>
            </div>
          </div>
        </section>
      <%end%>
      <%= yield %>
      <section class="content">
        <div class="container">
          <div class="row">
            <br>
          </div>
        </div>
      </section>
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-1 col-xs-3 col-sm-2 logo ">
              <a href="/"><img src="/site_assets/logo.jpg" alt=""></a>
            </div>
            <div class="col-lg-8 col-xs-9 col-sm-5 ">Copyrights 2030</div>
            <div class="col-lg-3 col-xs-12 col-sm-5 sociconcent">
              <ul class="socialicons">
                <li><a href="/"><i class="fa fa-facebook-square"></i></a></li>
                <li><a href="/"><i class="fa fa-twitter"></i></a></li>
                <li><a href="/"><i class="fa fa-cloud"></i></a></li>
                <li><a href="/"><i class="fa fa-rss"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="post">
  <div class="container">
    <div class="row">
      <% if question.errors.any? %>
        <div class="col-lg-8 col-md-8" style='margin-left: 130px;'>
          <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
          <ul>
            <% question.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="col-lg-4 col-md-4">
      </div>
    </div>
  </div>
  <%= form_with(model: question, class: "form newtopic") do |form| %>
    <div class="topwrap">
      <div class="userinfo pull-left">
        <div class="avatar">
          <img src="/site_assets/avatar4.jpg" alt="">
          <div class="status red">&nbsp;</div>
        </div>
        <div class="icons">
          <img src="/site_assets/icon3.jpg" alt=""><img src="/site_assets/icon4.jpg" alt=""><img src="/site_assets/icon5.jpg" alt=""><img src="/site_assets/icon6.jpg" alt="">
        </div>
      </div>
      <div class="posttext pull-left">
        <div>
          <%= form.text_field :title , placeholder: "Enter Question Title", class: "form-control"%>
        </div>
        <div>
          <%= form.text_area :description, placeholder: "Description", class: "form-control" %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="postinfobot">
      <div class="pull-right postreply">
        <div class="pull-left"><button type="submit" class="btn btn-primary">Create Question</button></div>
        <div class="clearfix"></div>
      </div>
      <div class="clearfix"></div>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="post" id="<%= dom_id question %>">
  <div class="wrap-ut pull-left">
    <div class="userinfo pull-left">
      <div class="avatar">
        <img src="<%= question.user.avatar ||  '/site_assets/avatar.jpg' %>" alt="">
        <div class="status green">&nbsp;</div>
      </div>
      <div class="icons">
        <img src="/site_assets/icon1.jpg" alt=""><img src="/site_assets/icon4.jpg" alt="">
      </div>
    </div>
    <div class="posttext pull-left">
      <h2><a href="<%= question_path(question)%>"><%= highlight(question.title, query_array) %></a></h2>
      <p><%= highlight(question.description, query_array) %></p>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="postinfo pull-left">
    <div class="comments">
      <div class="commentbg">
        <%= question.answers.count %>
        <div class="mark"></div>
      </div>
    </div>
    <div class="views"><i class="fa fa-eye"></i> 1,568</div>
    <div class="time"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(question.created_at) %></div>
  </div>
  <div class="postinfobot">
    <div class="posted pull-left"><i class="fa fa-clock-o"></i> Posted on : <%= h(question.created_at) %></div>
    <div class="next pull-right">
      <%if current_user && question.user == current_user%>
        <a href="<%= edit_question_path(question) %>"><i class="fa fa-edit"></i></a>
        <a data-turbo-method="delete" href="<%= question_path(question) %>"><i class="fa fa-trash-o"></i></a>
      <%end%>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<section class="content">
  <div class="container">
    <div class="row">
      <br>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8" id="questions">
        <% @questions.each do |question| %>
          <%= render question %>
        <% end %>
      </div>
      <div class="col-lg-4 col-md-4">
        <%= render 'shared/sidebar' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-xs-12">
        <%= paginate @questions %>
      </div>
    </div>
  </div>
</section>

app/views/questions/new.html.erb
<section class="content">
  <div class="container">
    <div class="row">
      <br>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8">
        <%= render "form", question: @question %>
      </div>
      <div class="col-lg-4 col-md-4">
        <%= render 'shared/sidebar' %>
      </div>
    </div>
  </div>
</section>

app/views/questions/show.html.erb
<section class="content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 breadcrumbf">
        <a href="/">Questions</a> <span class="diviver">&gt;</span> <a href="<%= question_path(@question)%>"><%=@question.title%></a>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8">
        <!-- POST -->
        <%= render @question %>
        <!-- POST -->
        <!-- POST -->
        <% @question.answers.each do |answer| %>
          <%= render answer %>
        <% end %>
        <% if current_user %>
          <%= render "answers/form", answer: Answer.new(question: @question, user: current_user) %>
        <%end%>
        <!-- POST -->
      </div>
      <div class="col-lg-4 col-md-4">
        <%= render 'shared/sidebar' %>
      </div>
    </div>
  </div>
</section>

app/views/shared/_sidebar.html.erb
<div class="sidebarblock">
  <h3>My Active Questions</h3>
  <% @current_user_questions.to_a.each do |question| %>
    <div class="divline"></div>
    <div class="blocktxt">
      <a href="<%= question_path(question) %>"><%= question.title %></a>
    </div>
  <% end %>